import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = Groq(api_key=os.environ["GROQ_API_KEY"])

_SYSTEM_PROMPT = """You are an AI content detection expert. Analyze the text provided and estimate the probability it was generated by an AI rather than written by a human.

Return ONLY a JSON object with a single key "score" whose value is a float between 0.0 and 1.0:
- 0.0 = almost certainly human-written
- 0.5 = uncertain / mixed signals
- 1.0 = almost certainly AI-generated

Consider: sentence variety, vocabulary naturalness, hedging language common in AI output, overly smooth logical flow, lack of idiosyncratic detail, and repetitive or formulaic phrasing."""


def classify_with_llm(text: str) -> float:
    """Return a 0-1 score for the probability that *text* is AI-generated."""
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Text to analyze:\n\n{text}"},
        ],
        response_format={"type": "json_object"},
        temperature=0.0,
    )
    result = json.loads(response.choices[0].message.content)
    score = float(result["score"])
    return max(0.0, min(1.0, score))
